{% set name = "parquet-tools" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 16f516e543356284812e2279244198a20015b05688b4ba40ef7cb6b5659b86ab

build:
  number: 0
  noarch: python
  entry_points:
    - parquet-tools = parquet_tools.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - boto3 >=1.13,<2.0
    - colorama >=0.4.3,<0.5.0
    - halo >=0.0.29,<0.0.30
    - pandas >=1,<2
    - pip
    - poetry-core >=1.0.0
    - pyarrow
    - python >=3.8
    - tabulate >=0.8.7,<0.9.0
    - thrift >=0.13.0,<0.14.0
  run:
    - boto3 >=1.13,<2.0
    - colorama >=0.4.3,<0.5.0
    - halo >=0.0.29,<0.0.30
    - pandas >=1,<2
    - pyarrow
    - python >=3.8
    - tabulate >=0.8.7,<0.9.0
    - thrift >=0.13.0,<0.14.0

test:
  imports:
    - parquet_tools
    - parquet_tools.commands
    - parquet_tools.gen_py
    - parquet_tools.gen_py.parquet
    - parquet_tools.parquet
  commands:
    - parquet-tools --help

about:
  home: https://github.com/ktrueda/parquet-tools
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Easy install parquet-tools

extra:
  recipe-maintainers:
    - jdblischak
