{% set name = "parquet-tools" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c34566a5cb293cdbce5d638fc82f208634f5d7611e53c3959adbb9060bd0816c

build:
  number: 0
  noarch: python
  entry_points:
    - parquet-tools = parquet_tools.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - boto3 >=1.13.25,<2.0.0
    - colorama >=0.4.3,<0.5.0
    - halo >=0.0.29,<0.0.30
    - pandas >=1.0.4,<2.0.0
    - pip
    - poetry >=0.12
    - pyarrow >=0.17.1,<0.18.0
    - python >=3.8
    - tabulate >=0.8.7,<0.9.0
    - thrift >=0.13.0,<0.14.0
  run:
    - boto3 >=1.13.25,<2.0.0
    - colorama >=0.4.3,<0.5.0
    - halo >=0.0.29,<0.0.30
    - pandas >=1.0.4,<2.0.0
    - pyarrow >=0.17.1,<0.18.0
    - python >=3.8
    - tabulate >=0.8.7,<0.9.0
    - thrift >=0.13.0,<0.14.0

test:
  imports:
    - parquet_tools
    - parquet_tools.commands
    - parquet_tools.gen_py
    - parquet_tools.gen_py.parquet
    - parquet_tools.parquet
  commands:
    - parquet-tools --help

about:
  home: https://github.com/ktrueda/parquet-tools
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Easy install parquet-tools

extra:
  recipe-maintainers:
    - jdblischak
    - ktrueda
