{% set name = "parquet-tools" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8deb439408d53ee7d2a89568c553e9e619915a13a452e0dd72e67a49e5f0867a

build:
  number: 1
  noarch: python
  entry_points:
    - parquet-tools = parquet_tools.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - halo >=0.0.29,<1
    - pyarrow
    - pandas >=1,<2
    - tabulate >=0.8.7,<1
    - boto3 >=1.13,<2
    - thrift >=0.13.0,<1
    - colorama >=0.4.3,1

test:
  imports:
    - parquet_tools
    - parquet_tools.commands
    - parquet_tools.gen_py
    - parquet_tools.gen_py.parquet
    - parquet_tools.parquet
  commands:
    - parquet-tools --help

about:
  home: https://github.com/ktrueda/parquet-tools
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Easy install parquet-tools

extra:
  recipe-maintainers:
    - jdblischak
